version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run:
        name: install helm
        command: .circleci/install.sh
    - run:
        name: set env tag
        command: echo "export TAG=$(cat helm/reporting-querying-chart/Chart.yaml | grep version | awk '{ print $2 }')" >> $BASH_ENV
    - run:
        name: helm lint
        command: helm lint ./helm/reporting-querying-chart
    - run:
        name: docker build
        command: docker build -t quay.io/giantswarm/reporting-querying:${TAG} .

  deploy:
    machine: true
    steps:
    - checkout

    - run:
        name: install helm
        command: .circleci/install.sh
    - run:
        name: set env tag
        command: echo "export TAG=$(cat helm/reporting-querying-chart/Chart.yaml | grep version | awk '{ print $2 }')" >> $BASH_ENV
    - run:
        name: helm lint
        command: helm lint ./helm/reporting-querying-chart
    - run:
        name: docker login
        command: docker login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
    - run:
        name: docker build
        command: docker build -t quay.io/giantswarm/reporting-querying:${TAG} .
    - run:
        name: Push to registry
        command: |
          docker push quay.io/giantswarm/reporting-querying:${TAG}
    - run:
        name: helm registry login
        command: helm registry login quay.io -u $QUAY_USERNAME -p $QUAY_PASSWORD
    - run:
        name: Push to registry
        command: cd helm/reporting-querying-chart && helm registry push quay.io --namespace giantswarm  --channel stable 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master