apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "querying.fullname" . }}
  
spec:
  schedule: {{ .Values.querying.schedule | quote}}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: reporting-querying
        spec:
          restartPolicy: Never
          imagePullPolicy: Always
          containers:
          - name: querying
            image: {{ .Values.querying.image }}:{{ .Values.querying.image_tag }}
            env:
            - name: ELASTICSEARCH_INDEX_URL_ALERTS
              value: {{ .Values.querying.elasticsearch_url }}/{{ .Values.querying.index }}
            - name: ELASTICSEARCH_INDEX_URL_PROCESSING
              value: {{ .Values.querying.elasticsearch_url }}/{{ .Values.querying.processor_index }}
            volumeMounts:
            - name: queries
              mountPath: /usr/src/app/queries.json
              subPath: queries.json
          volumes:
            - name: queries 
              configMap:
                # Provide the name of the ConfigMap containing the files you want
                # to add to the container
                name: {{ template "querying.fullname" . }}
