querying:
  image: quay.io/giantswarm/reporting-querying
  image_tag: latest
  index: alerts
  processor_index: processor-test1
  elasticsearch_url: http://reporting-tool-reporting-chart-elasticsearch.jgsqware-reporting-tool.svc:9200
  schedule: "*/1 * * * *"